config/routes.rb
# -*- encoding : utf-8 -*-
QdCollege::Application.routes.draw do
  root :to => 'home#index'
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.username=='CUI99JUAN' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, :controllers => {:registrations => "users/registrations"} do
    post '/users/check_uniq', :to => 'users/registrations#check_uniq'
  end

  post '/home/login_validate', :to => "home#login_validate"
  get '/lecturers', :to => "lecturers#index"

  match '/admin' => 'admin#index'
  match '/admin/index' => 'admin#index'
  get 'admin/logout'
  match '/admin/logout' => 'admin#logout'
  resources :beginners, :only => [:index,:show]
  resources :mediates, :only => [:index]
  resources :advanceds, :only => [:index]
  resources :games
  resources :users, :only => [:update,:edit] do
    collection{get :level,:exam,:fight}
  end
  resources :schools, :only => [:create,:show,:index] do
    collection{get :beginner,:mediate,:advanced}
  end
  resources :readings, :only=> [:show] do 
    get :download, :on=> :member
  end 
  resources :videos, :only=> [:show,:index] do 
    get :broadcast, :on=> :member
  end

  resources :fight_exams do
    get :home, :on => :collection
    get :regulations, :on => :collection
    get :start, :on => :collection
    post :next_stage, :on => :collection
    get :pause, :on => :collection
  end

  resources :ranking_lists do
    get :home, :on => :collection
    get :ranking_list_weeks, :on => :collection
    get :ranking_list_years, :on => :collection
  end

  devise_for :administrators
  namespace :admin do
    root :to => 'administrators#index'
    resources :games, :except => [:show]
    resources :awards, :except => [:show]
    resources :affiliates , :only => [:index]
    resources :documents do
      collection{post :order}
    end
    resources :videos do
      collection{post :order}
    end
    resources :video_nodes do
      collection{post :order}
    end
    
    resources :administrators
    resources :roles
    resources :permissions

    resources :question_onlines
    resources :question_stands
    resources :question_files do
      member{get :inport}
    end
    resources :taxons do
      get :search, :on => :collection
    end
    resources :regulations do
      post :update_positions, :on => :collection
    end
    resources :users ,:only=>[:index,:show] do
      get :reset_password , :on => :member
      get :enable , :on => :member
    end
    resources :award_records, :only=>[:index,:show]
    resources :ranking_list_years, :only=>[:index,:show]
    resources :ranking_list_weeks, :only=>[:index,:show]
    resources :advertisements do
      collection{post :order}
    end 
    resources :exam_records, :only=> [:index]
    resources :exams, :only=> [:index]

  end
end
#== Route Map
# Generated on 29 Oct 2013 22:18
#
#                        sidekiq_web        /sidekiq                                                      Sidekiq::Web
#                   users_check_uniq POST   /users/check_uniq(.:format)                                   users/registrations#check_uniq
#                      user_password POST   /users/password(.:format)                                     devise/passwords#create
#                  new_user_password GET    /users/password/new(.:format)                                 devise/passwords#new
#                 edit_user_password GET    /users/password/edit(.:format)                                devise/passwords#edit
#                                    PUT    /users/password(.:format)                                     devise/passwords#update
#           cancel_user_registration GET    /users/cancel(.:format)                                       users/registrations#cancel
#                  user_registration POST   /users(.:format)                                              users/registrations#create
#              new_user_registration GET    /users/sign_up(.:format)                                      users/registrations#new
#             edit_user_registration GET    /users/edit(.:format)                                         users/registrations#edit
#                                    PUT    /users(.:format)                                              users/registrations#update
#                                    DELETE /users(.:format)                                              users/registrations#destroy
#                       user_service GET    /users/service(.:format)                                      devise/cas_sessions#service
#               user_single_sign_out POST   /users/service(.:format)                                      devise/cas_sessions#single_sign_out
#                   new_user_session GET    /users/sign_in(.:format)                                      devise/cas_sessions#new
#          unregistered_user_session GET    /users/unregistered(.:format)                                 devise/cas_sessions#unregistered
#                       user_session POST   /users/sign_in(.:format)                                      devise/cas_sessions#create
#               destroy_user_session GET    /users/sign_out(.:format)                                     devise/cas_sessions#destroy
#                home_login_validate POST   /home/login_validate(.:format)                                home#login_validate
#                              admin        /admin(.:format)                                              admin#index
#                        admin_index        /admin/index(.:format)                                        admin#index
#                       admin_logout GET    /admin/logout(.:format)                                       admin#logout
#                                           /admin/logout(.:format)                                       admin#logout
#                          beginners GET    /beginners(.:format)                                          beginners#index
#                           beginner GET    /beginners/:id(.:format)                                      beginners#show
#                           mediates GET    /mediates(.:format)                                           mediates#index
#                          advanceds GET    /advanceds(.:format)                                          advanceds#index
#                              games GET    /games(.:format)                                              games#index
#                                    POST   /games(.:format)                                              games#create
#                           new_game GET    /games/new(.:format)                                          games#new
#                          edit_game GET    /games/:id/edit(.:format)                                     games#edit
#                               game GET    /games/:id(.:format)                                          games#show
#                                    PUT    /games/:id(.:format)                                          games#update
#                                    DELETE /games/:id(.:format)                                          games#destroy
#                        level_users GET    /users/level(.:format)                                        users#level
#                         exam_users GET    /users/exam(.:format)                                         users#exam
#                        fight_users GET    /users/fight(.:format)                                        users#fight
#                          edit_user GET    /users/:id/edit(.:format)                                     users#edit
#                               user PUT    /users/:id(.:format)                                          users#update
#                   beginner_schools GET    /schools/beginner(.:format)                                   schools#beginner
#                    mediate_schools GET    /schools/mediate(.:format)                                    schools#mediate
#                   advanced_schools GET    /schools/advanced(.:format)                                   schools#advanced
#                            schools POST   /schools(.:format)                                            schools#create
#                             school GET    /schools/:id(.:format)                                        schools#show
#                   download_reading GET    /readings/:id/download(.:format)                              readings#download
#                            reading GET    /readings/:id(.:format)                                       readings#show
#                    broadcast_video GET    /videos/:id/broadcast(.:format)                               videos#broadcast
#                             videos GET    /videos(.:format)                                             videos#index
#                              video GET    /videos/:id(.:format)                                         videos#show
#                   home_fight_exams GET    /fight_exams/home(.:format)                                   fight_exams#home
#            regulations_fight_exams GET    /fight_exams/regulations(.:format)                            fight_exams#regulations
#                  start_fight_exams GET    /fight_exams/start(.:format)                                  fight_exams#start
#             next_stage_fight_exams POST   /fight_exams/next_stage(.:format)                             fight_exams#next_stage
#                  pause_fight_exams GET    /fight_exams/pause(.:format)                                  fight_exams#pause
#                        fight_exams GET    /fight_exams(.:format)                                        fight_exams#index
#                                    POST   /fight_exams(.:format)                                        fight_exams#create
#                     new_fight_exam GET    /fight_exams/new(.:format)                                    fight_exams#new

app/models/administrator.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: administrators
#
#  id                 :integer          not null, primary key
#  user_name          :string(255)      not null
#  real_name          :string(255)
#  nick_name          :string(255)
#  email              :string(255)
#  encrypted_password :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Administrator < ActiveRecord::Base

  #users :cas_authenticatable
  devise :database_authenticatable

  attr_accessible :email, :nick_name, :user_name, :real_name , :affiliate_ids , :role_ids , :encrypted_password

  validates :user_name, :presence => true

  has_many :administrator_roles , :dependent => :destroy
  has_many :roles  , :through => :administrator_roles
  has_many :information

  has_many :administrator_affiliates , :dependent => :destroy
  has_many :affiliates , :through => :administrator_affiliates

  scope :search , lambda{|params|
    name_str = params[:user_name].present? ? params[:user_name].strip : ""
    roles_str = params[:role].present? ? params[:role].to_i : ""
    joins{administrator_roles}.where{
      conds = []
      conds << ( user_name =~ ("%" + name_str +"%") ) if params[:user_name].present?
      conds << ( administrator_roles.role_id == params[:role].to_i ) if params[:role].present?
      conds.inject{| conds_total , con |  conds_total &= con }
    }
  }

  def self.current
    Thread.current[:administrator]
  end
  def self.current=(user)
    Thread.current[:administrator] = user
  end

  def has_role?(title)
    roles.exists?(:level => title.to_s.downcase)
  end

  def admin?
    has_role?('superman')
  end
end

app/controllers/admin/administrators_controller.rb
# -*- encoding : utf-8 -*-
class Admin::AdministratorsController < Admin::ResourceController
  has_scope :search , :only => [:index] , :type => :hash
  #authorize_resource
  # inherit_resources
  
end

app/views/admin/administrators/_form.haml
= simple_form_for [ :admin, resource ], :html => { :class => 'form-horizontal' }  do |f|
  - attributes.each do |attr|
    = f.input attr
  = f.association :roles ,
   :collection => Role.all.each{|r|r.name = r.name+"(#{ Role::BASE_LEVEL.invert[r.level]  })" } , :as => :radio_buttons ,checked: resource.roles.first.try(:id)  
  = f.association :affiliates ,:as => :check_boxes , :class => false ,:item_wrapper_class => 'inline' , :label => false
  = f.submit :class => 'btn btn-primary'
=link_to t("#{resource_class.name.underscore}.back_list") , collection_path

:javascript
  $(function(){
    $(".alert input").click(
      function(){
        if( $(this).attr("checked") == "checked" ){
          $(this).parent().next().find("input:checkbox").attr("checked", true)
        }else{
          $(this).parent().next().find("input:checkbox").attr("checked", false)
        }
      })
  })
  

app/views/admin/administrators/_index.haml
= form_tag( collection_path , { :method => :get }) do
  %p
    用户名:
    = text_field_tag "search[user_name]" , params[:search].nil? ? "" : params[:search][:user_name]
    权限组:
    =collection_select(:search, :role, Role.all, :id, :name, :prompt => true ,
        :selected => params[:search].nil? ? "" : params[:search][:role].to_i)
    = submit_tag t("#{resource_class.name.underscore}.search")
%table{:class => "table table-bordered"}
  %thead
    %tr
      - (attributes+["roles","affiliates"]).each do |attr|
        %th= resource_class.human_attribute_name(attr)
      %th= "操作"
  %tbody
    - collection.each do |resource|
      %tr[resource]
        - (attributes+["roles","affiliates"]).each do |attr|
          - if respond_to?( "#{attr}_column".to_sym )
            %td= self.send( "#{attr}_column".to_sym )
          - elsif resource.send(attr).is_a? Time
            %td= l resource.send(attr)
          - elsif resource.send(attr).is_a? CarrierWave::Uploader::Base
            %td= image_tag( resource.send( attr + "_url" , :thumb ) )
          - elsif resource.send(attr).is_a?( TrueClass )
            %td 是
          - elsif resource.send(attr).is_a?( FalseClass )
            %td 否
          - elsif attr == "roles"
            %td
              - resource.roles.each{|r|r.name = r.name+"(#{ Role::BASE_LEVEL.invert[r.level]  })" }.each do|r|
                %span.nav= r.name
          - elsif attr == "affiliates"
            %td 
              - resource.affiliates.each do |a|
                %span.nav= a.name
          - else
            %td= resource.send(attr).to_s.truncate(20)
        %td
          = link_to t("#{resource_class.name.underscore}.show"), resource_path(resource)
          |
          = link_to t("#{resource_class.name.underscore}.edit"), edit_resource_path(resource)
          |
          = link_to t("#{resource_class.name.underscore}.destroy"), resource_path(resource), :method => :delete, :confirm => t("#{resource_class.name.underscore}.are_you_sure")
= paginate collection
= link_to t("#{resource_class.name.underscore}.new"), new_resource_path