config/routes.rb
# -*- encoding : utf-8 -*-
QdCollege::Application.routes.draw do
  root :to => 'home#index'
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.username=='CUI99JUAN' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, :controllers => {:registrations => "users/registrations"} do
    post '/users/check_uniq', :to => 'users/registrations#check_uniq'
  end

  post '/home/login_validate', :to => "home#login_validate"
  get '/lecturers', :to => "lecturers#index"

  match '/admin' => 'admin#index'
  match '/admin/index' => 'admin#index'
  get 'admin/logout'
  match '/admin/logout' => 'admin#logout'
  resources :beginners, :only => [:index,:show]
  resources :mediates, :only => [:index]
  resources :advanceds, :only => [:index]
  resources :games
  resources :users, :only => [:update,:edit] do
    collection{get :level,:exam,:fight}
  end
  resources :schools, :only => [:create,:show,:index] do
    collection{get :beginner,:mediate,:advanced}
  end
  resources :readings, :only=> [:show] do 
    get :download, :on=> :member
  end 
  resources :videos, :only=> [:show,:index] do 
    get :broadcast, :on=> :member
  end

  resources :fight_exams do
    get :home, :on => :collection
    get :regulations, :on => :collection
    get :start, :on => :collection
    post :next_stage, :on => :collection
    get :pause, :on => :collection
  end

  resources :ranking_lists do
    get :home, :on => :collection
    get :ranking_list_weeks, :on => :collection
    get :ranking_list_years, :on => :collection
  end

  devise_for :administrators
  namespace :admin do
    root :to => 'administrators#index'
    resources :games, :except => [:show]
    resources :awards, :except => [:show]
    resources :affiliates , :only => [:index]
    resources :documents do
      collection{post :order}
    end
    resources :videos do
      collection{post :order}
    end
    resources :video_nodes do
      collection{post :order}
    end
    
    resources :administrators
    resources :roles
    resources :permissions

    resources :question_onlines
    resources :question_stands
    resources :question_files do
      member{get :inport}
    end
    resources :taxons do
      get :search, :on => :collection
    end
    resources :regulations do
      post :update_positions, :on => :collection
    end
    resources :users ,:only=>[:index,:show] do
      get :reset_password , :on => :member
      get :enable , :on => :member
    end
    resources :award_records, :only=>[:index,:show]
    resources :ranking_list_years, :only=>[:index,:show]
    resources :ranking_list_weeks, :only=>[:index,:show]
    resources :advertisements do
      collection{post :order}
    end 
    resources :exam_records, :only=> [:index]
    resources :exams, :only=> [:index]

  end
end
#== Route Map
# Generated on 29 Oct 2013 22:18
#
#                        sidekiq_web        /sidekiq                                                      Sidekiq::Web
#                   users_check_uniq POST   /users/check_uniq(.:format)                                   users/registrations#check_uniq
#                      user_password POST   /users/password(.:format)                                     devise/passwords#create
#                  new_user_password GET    /users/password/new(.:format)                                 devise/passwords#new
#                 edit_user_password GET    /users/password/edit(.:format)                                devise/passwords#edit
#                                    PUT    /users/password(.:format)                                     devise/passwords#update
#           cancel_user_registration GET    /users/cancel(.:format)                                       users/registrations#cancel
#                  user_registration POST   /users(.:format)                                              users/registrations#create
#              new_user_registration GET    /users/sign_up(.:format)                                      users/registrations#new
#             edit_user_registration GET    /users/edit(.:format)                                         users/registrations#edit
#                                    PUT    /users(.:format)                                              users/registrations#update
#                                    DELETE /users(.:format)                                              users/registrations#destroy
#                       user_service GET    /users/service(.:format)                                      devise/cas_sessions#service
#               user_single_sign_out POST   /users/service(.:format)                                      devise/cas_sessions#single_sign_out
#                   new_user_session GET    /users/sign_in(.:format)                                      devise/cas_sessions#new
#          unregistered_user_session GET    /users/unregistered(.:format)                                 devise/cas_sessions#unregistered
#                       user_session POST   /users/sign_in(.:format)                                      devise/cas_sessions#create
#               destroy_user_session GET    /users/sign_out(.:format)                                     devise/cas_sessions#destroy
#                home_login_validate POST   /home/login_validate(.:format)                                home#login_validate
#                              admin        /admin(.:format)                                              admin#index
#                        admin_index        /admin/index(.:format)                                        admin#index
#                       admin_logout GET    /admin/logout(.:format)                                       admin#logout
#                                           /admin/logout(.:format)                                       admin#logout
#                          beginners GET    /beginners(.:format)                                          beginners#index
#                           beginner GET    /beginners/:id(.:format)                                      beginners#show
#                           mediates GET    /mediates(.:format)                                           mediates#index
#                          advanceds GET    /advanceds(.:format)                                          advanceds#index
#                              games GET    /games(.:format)                                              games#index
#                                    POST   /games(.:format)                                              games#create
#                           new_game GET    /games/new(.:format)                                          games#new
#                          edit_game GET    /games/:id/edit(.:format)                                     games#edit
#                               game GET    /games/:id(.:format)                                          games#show
#                                    PUT    /games/:id(.:format)                                          games#update
#                                    DELETE /games/:id(.:format)                                          games#destroy
#                        level_users GET    /users/level(.:format)                                        users#level
#                         exam_users GET    /users/exam(.:format)                                         users#exam
#                        fight_users GET    /users/fight(.:format)                                        users#fight
#                          edit_user GET    /users/:id/edit(.:format)                                     users#edit
#                               user PUT    /users/:id(.:format)                                          users#update
#                   beginner_schools GET    /schools/beginner(.:format)                                   schools#beginner
#                    mediate_schools GET    /schools/mediate(.:format)                                    schools#mediate
#                   advanced_schools GET    /schools/advanced(.:format)                                   schools#advanced
#                            schools POST   /schools(.:format)                                            schools#create
#                             school GET    /schools/:id(.:format)                                        schools#show
#                   download_reading GET    /readings/:id/download(.:format)                              readings#download
#                            reading GET    /readings/:id(.:format)                                       readings#show
#                    broadcast_video GET    /videos/:id/broadcast(.:format)                               videos#broadcast
#                             videos GET    /videos(.:format)                                             videos#index
#                              video GET    /videos/:id(.:format)                                         videos#show
#                   home_fight_exams GET    /fight_exams/home(.:format)                                   fight_exams#home
#            regulations_fight_exams GET    /fight_exams/regulations(.:format)                            fight_exams#regulations
#                  start_fight_exams GET    /fight_exams/start(.:format)                                  fight_exams#start
#             next_stage_fight_exams POST   /fight_exams/next_stage(.:format)                             fight_exams#next_stage
#                  pause_fight_exams GET    /fight_exams/pause(.:format)                                  fight_exams#pause
#                        fight_exams GET    /fight_exams(.:format)                                        fight_exams#index
#                                    POST   /fight_exams(.:format)                                        fight_exams#create
#                     new_fight_exam GET    /fight_exams/new(.:format)                                    fight_exams#new

app/controllers/intermediates_controller.rb
# -*- encoding : utf-8 -*-
class IntermediatesController < ApplicationController
  def index
	@documents= Document.sti_in_document("Document").search({:level=>"mediate"}).order_position.page(params[:page]).per(5)
	@videos= Video.search({:level=>"mediate"}).order_position
  end
end

app/helpers/intermediates_helper.rb
# -*- encoding : utf-8 -*-
module IntermediatesHelper
end

app/views/intermediates/index.html.erb
<%= javascript_include_tag 'jquery/jquery.marquee' %>
<script type="text/javascript">
    $(function(){
        $('#video_lists').marquee({auto: true, interval: 2000, showNum: 6, direction:'forward', stepLen: 1, speed: 1000, prevBtnId: 'prev', nextBtnId: 'next'});
        $('.video_img_selector').click(function(){
          $(this).parent('div').addClass('video_small_checked').siblings('div').removeClass('video_small_checked');
          $("#video_box_index img").attr('src',$(this).attr('bak'));
          $("#video_box_index a").attr('href',$(this).attr('href'));
          return false;
        })
    })
</script>

<div class="breadcrumb breadcrumb2">当前位置：<a href="/">首页</a> > <span>中级课堂视频</span></div>
<div class="clear"></div>
<!--wrapleft begin-->
<div class="wl_zxcp left">
  <div class="rim_main">
    <div class="bordertop">
      <div class="video_top" id="video_box_index">
        <% current_video= @videos.try(:first) %>
        <% unless @videos.present? %>
          <img src="/assets/images/middle_class/video.jpg" width="674" height="381" />
        <% else %>
          <a href="<%= video_path(current_video) %>">
            <img src="<%= @videos.first.logo.link_url(:large) %>" width="674" height="381" border="0"/>
          </a>
        <% end %>
      </div>
      <div class="video_down">

        <div class="video_down_left_button left">
          <a href="javascript:void(0)" id="prev"></a>
        </div>
      
        <div class="left" id="video_lists">
          <div class="ul">
            <!-- <div class="video_small li left video_small_checked"><img src="/assets/images/middle_class/video_small.jpg" width="86" height="49" /></div>
            <div class="video_small li left"><img src="/assets/images/middle_class/video_small.jpg" width="86" height="49" /></div>
            <div class="video_small li left"><img src="/assets/images/middle_class/video_small.jpg" width="86" height="49" /></div>
            <div class="video_small li left"><img src="/assets/images/middle_class/video_small.jpg" width="86" height="49" /></div>
            <div class="video_small li left"><img src="/assets/images/middle_class/video_small.jpg" width="86" height="49" /></div>
            <div class="video_small li left"><img src="/assets/images/middle_class/video_small.jpg" width="86" height="49" /></div> -->

            <% @videos.present? and @videos.each do |video| %>
              <div class="video_small left <%= "video_small_checked" if video==current_video %>">
                <a href="<%= video_path(video) %>" class="video_img_selector" bak="<%= video.logo.link_url(:large) %>">
                  <img src="<%= video.logo.link_url(:small) %>" width="86" height="49" />
                </a>
              </div>
            <% end  %>

          </div>
        </div>
      
        <div class="video_down_right_button right">
          <a href="javascript:void(0)" id="next"></a>
        </div>

      <div class="clear"></div>
      </div>
    </div>
  </div>
  <div class="rim_bottom"></div>
</div>
<!--wrapleft end-->
<!--wrapright begin-->
<div class="wr_zxcp right">
  <div class="zxcp">
    <a href="<%=mediate_schools_path %>"></a>
  </div>
</div>
<!--wrapright end-->
<div class="clear"></div>
<!--testbody begin-->
<div class="warpbox">
  <div class="bordertop">
    <div class="title">
      <div class="title_left left">在线阅读与下载</div>
    </div>
    <% @documents.present? and @documents.each do |document| %>
    <div class="readbox">
      <div class="readbox_left_1 left">
        <img src="<%= document.logo.link_url(:file_small)  %>" width="123" height="90" />
      </div>
      <div class="readbox_right right">
        <div class="readbox_title left">
          <%= document.title.truncate(20) %>
        </div>
        <div class="readbox_zz left">
          <div class="readbox_zz_left left">
            <div class="readbox_author left">作者：
              <span style="color:#0095ba;"><%= document.author %></span>
            </div>
            <!-- <div class="readbox_author left">页数：<span style="color:#0095ba;">123456</span></div> -->
          </div>
          <div class="readbox_zz_right right">
            <div class="readbox_read left">在线阅读：
              <span style="color:#9b9b9b;"><%= document.view_count %></span>
            </div>
            <div class="readbox_download right">下载：
              <span style="color:#9b9b9b;"><%= document.download_count %></span>
            </div>
          </div>
        </div>
        <div class="readbox_text right">
          <%= document.body %>
        </div>
      </div>
      <div class="readbutton right">
        <div class="read_button left">
          <%= link_to_if(document.can_view?, "在线阅读" , reading_path(document) ){
              link_to "在线阅读","javascript:alert('当前资料不允许阅读,请阅读其他本站资料!')"
          } %>
        </div>
        <div class="download_button left">
          <!-- <a href="<%#= download_reading_path(document) %>">下载</a> -->
          <%= link_to_if(document.can_download?, "下载" , download_reading_path(document) ){
              link_to "下载","javascript:alert('当前资料不允许下载,请下载其他本站资料!')"
          } %>
        </div>
      </div>
    </div>
    <% end  %>
    <div class="clear"></div>
</div>
<!--paging begin-->
<div class=" pagination3 right">
  <%= paginate @documents %>
</div>

<!--paging end-->
</div>
<div class="footbox_border"></div>
<!--testbody end-->