config/routes.rb
# -*- encoding : utf-8 -*-
QdCollege::Application.routes.draw do
  root :to => 'home#index'
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.username=='CUI99JUAN' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, :controllers => {:registrations => "users/registrations"} do
    post '/users/check_uniq', :to => 'users/registrations#check_uniq'
  end

  post '/home/login_validate', :to => "home#login_validate"
  get '/lecturers', :to => "lecturers#index"

  match '/admin' => 'admin#index'
  match '/admin/index' => 'admin#index'
  get 'admin/logout'
  match '/admin/logout' => 'admin#logout'
  resources :beginners, :only => [:index,:show]
  resources :mediates, :only => [:index]
  resources :advanceds, :only => [:index]
  resources :games
  resources :users, :only => [:update,:edit] do
    collection{get :level,:exam,:fight}
  end
  resources :schools, :only => [:create,:show,:index] do
    collection{get :beginner,:mediate,:advanced}
  end
  resources :readings, :only=> [:show] do 
    get :download, :on=> :member
  end 
  resources :videos, :only=> [:show,:index] do 
    get :broadcast, :on=> :member
  end

  resources :fight_exams do
    get :home, :on => :collection
    get :regulations, :on => :collection
    get :start, :on => :collection
    post :next_stage, :on => :collection
    get :pause, :on => :collection
  end

  resources :ranking_lists do
    get :home, :on => :collection
    get :ranking_list_weeks, :on => :collection
    get :ranking_list_years, :on => :collection
  end

  devise_for :administrators
  namespace :admin do
    root :to => 'administrators#index'
    resources :games, :except => [:show]
    resources :awards, :except => [:show]
    resources :affiliates , :only => [:index]
    resources :documents do
      collection{post :order}
    end
    resources :videos do
      collection{post :order}
    end
    resources :video_nodes do
      collection{post :order}
    end
    
    resources :administrators
    resources :roles
    resources :permissions

    resources :question_onlines
    resources :question_stands
    resources :question_files do
      member{get :inport}
    end
    resources :taxons do
      get :search, :on => :collection
    end
    resources :regulations do
      post :update_positions, :on => :collection
    end
    resources :users ,:only=>[:index,:show] do
      get :reset_password , :on => :member
      get :enable , :on => :member
    end
    resources :award_records, :only=>[:index,:show]
    resources :ranking_list_years, :only=>[:index,:show]
    resources :ranking_list_weeks, :only=>[:index,:show]
    resources :advertisements do
      collection{post :order}
    end 
    resources :exam_records, :only=> [:index]
    resources :exams, :only=> [:index]

  end
end
#== Route Map
# Generated on 29 Oct 2013 22:18
#
#                        sidekiq_web        /sidekiq                                                      Sidekiq::Web
#                   users_check_uniq POST   /users/check_uniq(.:format)                                   users/registrations#check_uniq
#                      user_password POST   /users/password(.:format)                                     devise/passwords#create
#                  new_user_password GET    /users/password/new(.:format)                                 devise/passwords#new
#                 edit_user_password GET    /users/password/edit(.:format)                                devise/passwords#edit
#                                    PUT    /users/password(.:format)                                     devise/passwords#update
#           cancel_user_registration GET    /users/cancel(.:format)                                       users/registrations#cancel
#                  user_registration POST   /users(.:format)                                              users/registrations#create
#              new_user_registration GET    /users/sign_up(.:format)                                      users/registrations#new
#             edit_user_registration GET    /users/edit(.:format)                                         users/registrations#edit
#                                    PUT    /users(.:format)                                              users/registrations#update
#                                    DELETE /users(.:format)                                              users/registrations#destroy
#                       user_service GET    /users/service(.:format)                                      devise/cas_sessions#service
#               user_single_sign_out POST   /users/service(.:format)                                      devise/cas_sessions#single_sign_out
#                   new_user_session GET    /users/sign_in(.:format)                                      devise/cas_sessions#new
#          unregistered_user_session GET    /users/unregistered(.:format)                                 devise/cas_sessions#unregistered
#                       user_session POST   /users/sign_in(.:format)                                      devise/cas_sessions#create
#               destroy_user_session GET    /users/sign_out(.:format)                                     devise/cas_sessions#destroy
#                home_login_validate POST   /home/login_validate(.:format)                                home#login_validate
#                              admin        /admin(.:format)                                              admin#index
#                        admin_index        /admin/index(.:format)                                        admin#index
#                       admin_logout GET    /admin/logout(.:format)                                       admin#logout
#                                           /admin/logout(.:format)                                       admin#logout
#                          beginners GET    /beginners(.:format)                                          beginners#index
#                           beginner GET    /beginners/:id(.:format)                                      beginners#show
#                           mediates GET    /mediates(.:format)                                           mediates#index
#                          advanceds GET    /advanceds(.:format)                                          advanceds#index
#                              games GET    /games(.:format)                                              games#index
#                                    POST   /games(.:format)                                              games#create
#                           new_game GET    /games/new(.:format)                                          games#new
#                          edit_game GET    /games/:id/edit(.:format)                                     games#edit
#                               game GET    /games/:id(.:format)                                          games#show
#                                    PUT    /games/:id(.:format)                                          games#update
#                                    DELETE /games/:id(.:format)                                          games#destroy
#                        level_users GET    /users/level(.:format)                                        users#level
#                         exam_users GET    /users/exam(.:format)                                         users#exam
#                        fight_users GET    /users/fight(.:format)                                        users#fight
#                          edit_user GET    /users/:id/edit(.:format)                                     users#edit
#                               user PUT    /users/:id(.:format)                                          users#update
#                   beginner_schools GET    /schools/beginner(.:format)                                   schools#beginner
#                    mediate_schools GET    /schools/mediate(.:format)                                    schools#mediate
#                   advanced_schools GET    /schools/advanced(.:format)                                   schools#advanced
#                            schools POST   /schools(.:format)                                            schools#create
#                             school GET    /schools/:id(.:format)                                        schools#show
#                   download_reading GET    /readings/:id/download(.:format)                              readings#download
#                            reading GET    /readings/:id(.:format)                                       readings#show
#                    broadcast_video GET    /videos/:id/broadcast(.:format)                               videos#broadcast
#                             videos GET    /videos(.:format)                                             videos#index
#                              video GET    /videos/:id(.:format)                                         videos#show
#                   home_fight_exams GET    /fight_exams/home(.:format)                                   fight_exams#home
#            regulations_fight_exams GET    /fight_exams/regulations(.:format)                            fight_exams#regulations
#                  start_fight_exams GET    /fight_exams/start(.:format)                                  fight_exams#start
#             next_stage_fight_exams POST   /fight_exams/next_stage(.:format)                             fight_exams#next_stage
#                  pause_fight_exams GET    /fight_exams/pause(.:format)                                  fight_exams#pause
#                        fight_exams GET    /fight_exams(.:format)                                        fight_exams#index
#                                    POST   /fight_exams(.:format)                                        fight_exams#create
#                     new_fight_exam GET    /fight_exams/new(.:format)                                    fight_exams#new

app/models/video.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: documents
#
#  id             :integer          not null, primary key
#  title          :string(255)
#  body           :text
#  author         :string(255)
#  level          :string(255)
#  topic          :string(255)
#  can_download   :boolean          default(FALSE)
#  can_view       :boolean          default(FALSE)
#  position       :integer          default(0)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  download_count :integer          default(0)
#  view_count     :integer          default(0)
#  type           :string(255)      default("Document")
#

# -*- encoding : utf-8 -*-
# -*- encoding : utf-8 -*-
# -*- encoding : utf-8 -*-
class Video < Document
  attr_accessible :body, :level, :title, :topic, :author
  has_many :video_nodes,dependent: :destroy
end

app/controllers/admin/videos_controller.rb
# -*- encoding : utf-8 -*-
class Admin::VideosController < Admin::DocumentsController
  defaults :resource_class => Video
  has_scope :sti_in_document, :default => resource_class.to_s

  private
	def build_associations
	  resource.build_logo unless resource.logo
	end
end

app/controllers/videos_controller.rb
# -*- encoding : utf-8 -*-
class VideosController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_user_level,:only=>[:show]
  def show
  	@video= Video.find_by_id params[:id]
  	if @video.type!= "Video"  or @video.blank?
  		render :text=> "对不起，您想查看的视频专题不存在" and return
  	end 
   @video.increment!(:view_count,1)
  	@video_nodes= @video.video_nodes.order_position.page(params[:page]).per(5)
  end

  def index 
	  	unless request.xhr?
	  		redirect_to :back and return 
	  	end 
	  	@video= Video.find_by_id params[:id]
	  	@video_nodes= @video.video_nodes.order_position.page(params[:page]).per(5)

  end 

  def broadcast
  		@video_node= VideoNode.find_by_id params[:id]	
  end 

  private 
    def check_user_level
      @document= Document.find_by_id params[:id]
      user_level= current_user.try(:student).try(:level) 
      able= case user_level
      when "mediate"
        ['mediate'].include? @document.try(:level)
      when "advanced"
        ['mediate', 'advanced'].include? @document.try(:level)
      else
        false
      end 

      unless able
        flash[:notice] = "您当前的级别不可以操作视频!"
        redirect_to(root_path)  and return
      end
    end

end

app/helpers/videos_helper.rb
# -*- encoding : utf-8 -*-
module VideosHelper
end

app/views/videos/_video_box.html.erb
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="655" height="371" id="cc_B1A08CDD096A9F99">
                  <param name="movie" value="<%= video_box.try(:link) %>" />
                  <param name="allowFullScreen" value="true" />
                  <param name="allowScriptAccess" value="always" />
                  <embed src="<%= video_box.try(:link) %>" width="655" height="371" name="cc_B1A08CDD096A9F99" allowFullScreen="true" allowScriptAccess="always" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash"/>
</object>
<input value="<%= video_box.try(:id) %>" id="cur_video" type="hidden"/>

app/views/videos/_video_node_lists.html.erb
<ul class="videolist">
  <% @video_nodes and @video_nodes.each do |v_n| %>
  <li class="<%#= "lihover" if v_n==@video_nodes.first %>" sign="<%= v_n.id %>" >
    <a href="<%= broadcast_video_path(v_n) %>" data-remote="true" title="<%= v_n.title %>" class="video_choser">
      <img src="<%= v_n.logo.try(:link_url,:small) if v_n.logo %>"  />
      <span>
        <!-- <strong>第一讲</strong> -->
        <%= v_n.title.truncate(25) %>
      </span>
    </a>
  </li>
  <% end  %>
</ul>
<!--pagination begin-->
<div class="pagination2">
  <%= paginate @video_nodes , :window=> 1, :params => {:controller => 'videos', :action => 'index'}, :remote => true %>
</div>

<!--pagination end-->
<script>
  $(function(){
    $('.videolist li').each(function(){
      if($('#cur_video').val()==$(this).attr('sign'))
        $(this).addClass('lihover');
    })
    $('.video_choser').click(function(){
      $(this).parent('li').addClass('lihover').siblings('li').removeClass('lihover');
    }) 
    $('.pagination .next_page a').text('>');
    $('.pagination .last a').text('>>');
    $('.pagination .first a').text("<<");
    $('.pagination .prev a').text("<");
  })
  
</script>

app/views/videos/broadcast.js.erb
$("#video_box").html(<%= raw render("video_box",:video_box=>@video_node).inspect %>)

app/views/videos/index.js.erb
$("#video_node_lists_box").html(<%=raw render( "video_node_lists" ).inspect %>)

app/views/videos/show.html.erb
<!--footbox begin-->
<div class="breadcrumb breadcrumb2">
  <% cur_path= case @video.level 
  when "mediate" then "/mediates"
  when  "advanced" then "/advanceds" 
    end %>
  当前位置：<a href="/">首页</a> > <a href="<%=  cur_path %>"><%= @video.level_text %>课堂</a> > <span><%= @video.level_text %>课堂视频</span>
</div>
<script type="text/javascript">
  $(function(){
    <%if cur_path=="/mediates"%>
      $('.nav3').addClass('ah3');
    <% elsif cur_path=="/advanceds"%>
      $('.nav4').addClass('ah4');
    <% end  %>
  })
</script>
<div class="warpbox">
  <div class="bordertop">
    <div class="zj_video">
      <h2><%= @video.title %><span>作者：<%= @video.author.truncate(25) %></span>
        <span>
        已有
        <strong><%= @video.view_count %></strong>
        人观看
        </span>
      </h2>
      <div class="zjvl left" id="video_box">
        <!-- <img src="/assets/images/video.jpg" width="655" height="371" /> -->
        <%= render("video_box",:video_box=>@video_nodes.first) %>

      </div>
      <div class="zjvr left" id="video_node_lists_box">
        <%= render "video_node_lists" %>
        
      </div>
    </div>
  </div>
</div>
<div class="footbox_border"></div>
<div class="warpbox">
  <div class="bordertop">
    <div class="say"></div>
    <div class="weibo">
      <!-- <img src="/assets/images/reading_online/weibo.jpg" width="921" height="527" /> -->
      <iframe id="weiboiframe" width="921" scrolling="auto" height="600" frameborder="0" src="http://wall.v.t.qq.com/index.php?c=wall&a=index&ak=801175828&w=0&h=600&o=7&s=0&t=<%= CGI.escape(@video.topic.strip) %>" name="weiboiframe"></iframe>
    </div>
    <div class="clear"></div>
  </div>
</div>
<div class="footbox_border"></div>