config/routes.rb
# -*- encoding : utf-8 -*-
QdCollege::Application.routes.draw do
  root :to => 'home#index'
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.username=='CUI99JUAN' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, :controllers => {:registrations => "users/registrations"} do
    post '/users/check_uniq', :to => 'users/registrations#check_uniq'
  end

  post '/home/login_validate', :to => "home#login_validate"
  get '/lecturers', :to => "lecturers#index"

  match '/admin' => 'admin#index'
  match '/admin/index' => 'admin#index'
  get 'admin/logout'
  match '/admin/logout' => 'admin#logout'
  resources :beginners, :only => [:index,:show]
  resources :mediates, :only => [:index]
  resources :advanceds, :only => [:index]
  resources :games
  resources :users, :only => [:update,:edit] do
    collection{get :level,:exam,:fight}
  end
  resources :schools, :only => [:create,:show,:index] do
    collection{get :beginner,:mediate,:advanced}
  end
  resources :readings, :only=> [:show] do 
    get :download, :on=> :member
  end 
  resources :videos, :only=> [:show,:index] do 
    get :broadcast, :on=> :member
  end

  resources :fight_exams do
    get :home, :on => :collection
    get :regulations, :on => :collection
    get :start, :on => :collection
    post :next_stage, :on => :collection
    get :pause, :on => :collection
  end

  resources :ranking_lists do
    get :home, :on => :collection
    get :ranking_list_weeks, :on => :collection
    get :ranking_list_years, :on => :collection
  end

  devise_for :administrators
  namespace :admin do
    root :to => 'administrators#index'
    resources :games, :except => [:show]
    resources :awards, :except => [:show]
    resources :affiliates , :only => [:index]
    resources :documents do
      collection{post :order}
    end
    resources :videos do
      collection{post :order}
    end
    resources :video_nodes do
      collection{post :order}
    end
    
    resources :administrators
    resources :roles
    resources :permissions

    resources :question_onlines
    resources :question_stands
    resources :question_files do
      member{get :inport}
    end
    resources :taxons do
      get :search, :on => :collection
    end
    resources :regulations do
      post :update_positions, :on => :collection
    end
    resources :users ,:only=>[:index,:show] do
      get :reset_password , :on => :member
      get :enable , :on => :member
    end
    resources :award_records, :only=>[:index,:show]
    resources :ranking_list_years, :only=>[:index,:show]
    resources :ranking_list_weeks, :only=>[:index,:show]
    resources :advertisements do
      collection{post :order}
    end 
    resources :exam_records, :only=> [:index]
    resources :exams, :only=> [:index]

  end
end
#== Route Map
# Generated on 29 Oct 2013 22:18
#
#                        sidekiq_web        /sidekiq                                                      Sidekiq::Web
#                   users_check_uniq POST   /users/check_uniq(.:format)                                   users/registrations#check_uniq
#                      user_password POST   /users/password(.:format)                                     devise/passwords#create
#                  new_user_password GET    /users/password/new(.:format)                                 devise/passwords#new
#                 edit_user_password GET    /users/password/edit(.:format)                                devise/passwords#edit
#                                    PUT    /users/password(.:format)                                     devise/passwords#update
#           cancel_user_registration GET    /users/cancel(.:format)                                       users/registrations#cancel
#                  user_registration POST   /users(.:format)                                              users/registrations#create
#              new_user_registration GET    /users/sign_up(.:format)                                      users/registrations#new
#             edit_user_registration GET    /users/edit(.:format)                                         users/registrations#edit
#                                    PUT    /users(.:format)                                              users/registrations#update
#                                    DELETE /users(.:format)                                              users/registrations#destroy
#                       user_service GET    /users/service(.:format)                                      devise/cas_sessions#service
#               user_single_sign_out POST   /users/service(.:format)                                      devise/cas_sessions#single_sign_out
#                   new_user_session GET    /users/sign_in(.:format)                                      devise/cas_sessions#new
#          unregistered_user_session GET    /users/unregistered(.:format)                                 devise/cas_sessions#unregistered
#                       user_session POST   /users/sign_in(.:format)                                      devise/cas_sessions#create
#               destroy_user_session GET    /users/sign_out(.:format)                                     devise/cas_sessions#destroy
#                home_login_validate POST   /home/login_validate(.:format)                                home#login_validate
#                              admin        /admin(.:format)                                              admin#index
#                        admin_index        /admin/index(.:format)                                        admin#index
#                       admin_logout GET    /admin/logout(.:format)                                       admin#logout
#                                           /admin/logout(.:format)                                       admin#logout
#                          beginners GET    /beginners(.:format)                                          beginners#index
#                           beginner GET    /beginners/:id(.:format)                                      beginners#show
#                           mediates GET    /mediates(.:format)                                           mediates#index
#                          advanceds GET    /advanceds(.:format)                                          advanceds#index
#                              games GET    /games(.:format)                                              games#index
#                                    POST   /games(.:format)                                              games#create
#                           new_game GET    /games/new(.:format)                                          games#new
#                          edit_game GET    /games/:id/edit(.:format)                                     games#edit
#                               game GET    /games/:id(.:format)                                          games#show
#                                    PUT    /games/:id(.:format)                                          games#update
#                                    DELETE /games/:id(.:format)                                          games#destroy
#                        level_users GET    /users/level(.:format)                                        users#level
#                         exam_users GET    /users/exam(.:format)                                         users#exam
#                        fight_users GET    /users/fight(.:format)                                        users#fight
#                          edit_user GET    /users/:id/edit(.:format)                                     users#edit
#                               user PUT    /users/:id(.:format)                                          users#update
#                   beginner_schools GET    /schools/beginner(.:format)                                   schools#beginner
#                    mediate_schools GET    /schools/mediate(.:format)                                    schools#mediate
#                   advanced_schools GET    /schools/advanced(.:format)                                   schools#advanced
#                            schools POST   /schools(.:format)                                            schools#create
#                             school GET    /schools/:id(.:format)                                        schools#show
#                   download_reading GET    /readings/:id/download(.:format)                              readings#download
#                            reading GET    /readings/:id(.:format)                                       readings#show
#                    broadcast_video GET    /videos/:id/broadcast(.:format)                               videos#broadcast
#                             videos GET    /videos(.:format)                                             videos#index
#                              video GET    /videos/:id(.:format)                                         videos#show
#                   home_fight_exams GET    /fight_exams/home(.:format)                                   fight_exams#home
#            regulations_fight_exams GET    /fight_exams/regulations(.:format)                            fight_exams#regulations
#                  start_fight_exams GET    /fight_exams/start(.:format)                                  fight_exams#start
#             next_stage_fight_exams POST   /fight_exams/next_stage(.:format)                             fight_exams#next_stage
#                  pause_fight_exams GET    /fight_exams/pause(.:format)                                  fight_exams#pause
#                        fight_exams GET    /fight_exams(.:format)                                        fight_exams#index
#                                    POST   /fight_exams(.:format)                                        fight_exams#create
#                     new_fight_exam GET    /fight_exams/new(.:format)                                    fight_exams#new

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
  end

  def login_validate
    #return json {:result => true/false, :global_id => id }
    session[:user_return_to] = nil
    response = Faraday.post('http://sso.glodon.com/bit_client_sessions/login', {loginname: params[:loginname], password: params[:password]})
    if JSON.parse(response.body)['result']
      render :json => {:result => true}.to_json
    else
      render :json => {:result => false, :error_message => '用户名或密码不正确'}
    end
  end
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/views/home/index.html.erb
<script>
    function is_blank(text){
        return (text == undefined || text == '' || text == null) ? true : false
    }
    $(function(){

        $("form input[name='loginname'], form input[name='password']").blur(function(){
            $('#login_error_message').hide();
        });
        $("form input[type='submit']").click(function(){
            if(is_blank($("form input[name='loginname']").val())){
                $('#login_error_message').show().html('用户名不能为空');
                return false;
            }
            if(is_blank($("form input[name='password']").val())){
                $('#login_error_message').show().html('密码不能为空');
                return false;
            }
            $.post('/home/login_validate', $('form').serialize(), function(msg){
                if(msg.result){
                    fm.submit();
                }else{
                    $('#login_error_message').show().html('用户名或密码不正确');
                }
            }, "json");
            return false;
        })
    })
</script>
<!--wrapleft begin-->
<div class="wl left">
  <div class="rim_main">
    <div class="bordertop">
      <h2 class="tit"><p><span>清单知识进阶攻略</span></p></h2>
      <dl class="cj">
        <dt><img src="/assets/images/jz_13.jpg" width="142" height="37" />掌握清单初级基础知识</dt>
        <dd>
          <p>本课堂主要内容为《GB50500-2013建设工程工程量清单计价规范》中条款的自我学习，</p>
          <p> 通过【在线测评】栏目对清单规范的掌握进行测试考核，考核内容将从初级题库中随机抽取50道形成试卷，在30分钟内完成答题且<span style="color:red;">通过率为60%</span>者可顺利进入中级课堂学习或进入【一战到底】知识大通关游戏，通过同时还将获得一次幸运抽奖机会！（仅限首次通过）</p></dd>
        <dd>
          <% if user_signed_in? %>
              <a href="/beginners" class="kta1">进入初级课堂</a> <a href="/schools/beginner" class="kta2">初级在线评测</a>
          <% else %>
              <a href="javascript:alert('请您先登录！');location.href='/users/sign_in';" class="kta1">进入初级课堂</a> <a href="javascript:alert('请您先登录!');location.href='/users/sign_in';" class="kta2">初级在线评测</a>
          <% end %>
          <p class="cjrs">已有<span><%= beginner_student_count %></span>人参加</p>
        </dd>
      </dl>

      <dl class="zj">
        <dt><img src="/assets/images/jz_42.jpg" width="142" height="37" />掌握清单中级基础知识</dt>
        <dd>
          <p>本课堂主要内容为马楠教授讲解【2013版《清单计价规范》十大亮点解读与关键应用操作】，主要对新清单背景、十大变化、实战案例、应用展望做了详细解析；</p>
          <p>提供在线浏览、课件下载等功能方便用户随时随地学习；</p>
          <p> 通过【在线测评】栏目对本课堂内容掌握情况进行考核，考核内容将从中级题库中随机抽取20道形成考卷，在20分钟内完成答题且<span style="color:red;">通过率为80%</span>者则顺利进入高级课堂继续学习或进入【一战到底】知识大通关游戏，通过同时还将获得一次幸运抽奖机会！（仅限首次通过）</p></dd>
        <dd>
          <% if user_signed_in? %>
              <% if ["mediate", "advanced"].include? current_user.try(:student).try(:level) %>
                  <a href="/mediates" class="kta1">进入中级课堂</a> <a href="/schools/mediate" class="kta2">中级在线评测</a>
              <% else %>
                  <a href="javascript:alert('您的等级还不够！，不能进入中级课堂');" class="kta22">进入中级课堂</a> <a href="javascript:alert('您的等级还不够！，不能进行中级评测');" class="kta12">中级在线评测</a>
              <% end %>
          <% else %>
              <a href="javascript:alert('请您先登录！');location.href='/users/sign_in';" class="kta1">进入中级课堂</a> <a href="javascript:alert('请您先登录！');location.href='/users/sign_in';" class="kta2">中级在线评测</a>
          <% end %>
          <p class="cjrs2">已有<span><%= mediate_student_count %></span>人参加</p>
        </dd>
      </dl>

      <dl class="gj">
        <dt><img src="/assets/images/jz_61.jpg" width="142" height="37" />掌握清单高级基础知识</dt>
        <dd>
          <p>本课堂主要内容为马楠教授结合实际案例讲解【2013《清单计价规范》实施中亟需解决的 十大难点热点问题解决策略】</p>
          <p>提供在线浏览、课件下载等功能方便用户随时随地学习；</p>
          <p> 通过【在线测评】栏目对本课堂内容掌握情况进行考核，考核内容将从高级题库中随机抽取20道形成考卷，在20分钟内答题完成且<span style="color:red;">通过率为80%</span>者则顺利完成本学院现阶段所有课程学习，可进入【一战到底】大通关中进一步验证自己的学习成果，通过同时还将获得一次幸运抽奖机会！（仅限首次通过）</p></dd>
        <dd>
          <% if user_signed_in? %>
              <% if ["advanced"].include? current_user.try(:student).try(:level) %>
                  <a href="/advanceds" class="kta1">进入高级课堂</a> <a href="/schools/advanced" class="kta2">高级在线评测</a>
              <% else %>
                  <a href="javascript:alert('您的等级还不够！，不能进入高级课堂');" class="kta22">进入高级课堂</a> <a href="javascript:alert('您的等级还不够！，不能进行高级评测');" class="kta12">高级在线评测</a>
              <% end %>
          <% else %>
              <a href="javascript:alert('请您先登录！');location.href='/users/sign_in';" class="kta1">进入高级课堂</a> <a href="javascript:alert('请您先登录！');location.href='/users/sign_in';" class="kta2">高级在线评测</a>
          <% end %>
          <p class="cjrs">已有<span><%= advanced_student_count %></span>人参加</p>
        </dd>
      </dl>

    </div>
  </div>
  <div class="rim_bottom"></div>
</div>
<!--wrapleft end-->
<!--wrapleft begin-->
<div class="wr right">
  <div class="login" style="height: <%= current_user ? 290 : 227 %>px;">
    <div class="bordertop" style="height: 227px;">
      <% if current_user %>
          <ul class="landing">
            <li title="<%= current_user.username %>">帐号：<%= current_user.username.try(:truncate, 20) %></li>
            <li>姓名：<%= current_user.name || '未填写' %></li>
            <li>级别：<%= current_user.level_text %></li>
            <li>所属地区：<%= current_user.zone_full_name || '未填写' %> </li>
          </ul>
          <!--jintpm begin-->
          <ol class="jintpm">
            <li>今天的排名：</li>
            <li>一战到底：<%= current_user.home_fight_rank %><img src="/assets/images/two/<%= current_user.fight_rank_change %>.jpg" /></li>
            <li>初<i>级：</i><%= current_user.home_beginner_rank %><img src="/assets/images/two/<%= current_user.beginner_rank_change %>.jpg" /></li>
            <li>中<i>级：</i><%= current_user.home_mediate_rank %><img src="/assets/images/two/<%= current_user.mediate_rank_change %>.jpg" /></li>
            <li>高<i>级：</i><%= current_user.home_advanced_rank %><img src="/assets/images/two/<%= current_user.advanced_rank_change %>.jpg" /></li>
          </ol>
          <!--jintpm end-->
          <div class="logina"><input name="" type="button" class="loginbtn" value="进入用户中心" onclick="javascript: location.href = '/users/edit'"/></div>
      <% else %>
          <%= form_tag Setting.frontend_cas_login_request_url, :name => "fm" do |f| %>
              <h2 class="tit tit2"><span>我的用户中心</span></h2>
              <input name="service" type="hidden" value="http://<%=request.host_with_port%>/users/service" class="passwordbj" />
              <span id="login_error_message" class="tip" style="display:none; font-size: 12px;color: red; margin-left:25px; margin-top: 5px;">用户名或密码不正确</span>
              <input name="loginname" type="text" placeholder="登录帐号或邮箱" class="ueserbj" />
              <input name="password" type="password" value="" placeholder="" class="passwordbj" />
              <div class="logina"><input name="" type="submit" class="loginbtn" value="登录" />
                <%= link_to "忘记密码?", new_password_path(:user) %>
              </div>
              <div class="logina2">还没有账号？<a href="/users/sign_up">立即注册</a>！</div>
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="wrborbot"></div>

  <div class="yzdd">
    一战到底栏目，是通过闯关答题、积分排行的模式，让选手达到对清单及软件知识的全面掌握。在收获知识的同时看看身边的朋友谁会比你更厉害。一战到底前10名选手还有礼品获得。
    <%= link_to '', home_fight_exams_path %>
  </div>

  <script type="text/javascript">
      $(function(){
          $(".paihb > a").click(function(){
              $(this).addClass("paihbhover").siblings().removeClass("paihbhover");
              $("table."+$(this).attr("id")).show().siblings("table").hide();
              $("#rank_href").attr("href", $(this).attr("href"));
              return false;
          })
      })
  </script>

  <!--ranking_list begin-->
  <div class="ranking_list" style="height: <%= current_user ? 386 : 449 %>px;">
    <div class="bordertop">
      <h2 class="tit tit2"><span>排行榜</span><a href="/ranking_lists/home" target="_blank" id="rank_href">查看更多>></a></h2>
      <div class="paihb"><a href="/ranking_lists/home" class="paihbhover" id="fight_rank">一战到底</a>
        <a href="/schools" id="beginner_rank">初级</a>
        <a href="/schools" id="mediate_rank">中级</a>
        <a href="/schools" class="paihbgj" id="advanced_rank">高级</a>
      </div>

      <table width="100%" border="0" cellspacing="0" cellpadding="0" style="table-layout:fixed;word-break:break-all;" class="fight_rank">
        <tr>
          <th scope="col">名次</th>
          <th scope="col">姓名</th>
          <th scope="col">地区</th>
          <th scope="col">金币</th>
        </tr>
        <% @ranking_list_years = RankingListYear.where(" gold_count > 0 ").reorder(' gold_count desc, ranking_lists.created_at asc ').limit(6) %>
        <% @ranking_list_years.each_with_index do |rly, index| %>
            <tr>
              <td class="<%= index == 0 ? 'tdnumber' : 'tdnum' %>"><span><%= index + 1 %></span></td>
              <td title="<%= (rly.name || rly.username || '') %>"><%= (rly.name || rly.username || '').truncate(5, :omission => '') %></td>
              <td><%= rly.user.zone_province_name %></td>
              <td><%= rly.gold_count %></td>
            </tr>
        <% end %>
      </table>

      <% User.level.values.each do |lv| %>
          <table width="100%" border="0" cellspacing="0" cellpadding="0" style="table-layout:fixed;word-break:break-all;display: none;" class="<%= lv %>_rank">
            <tr>
              <th scope="col">名次</th>
              <th scope="col">姓名</th>
              <th scope="col">地区</th>
              <th scope="col">正确数</th>
            </tr>
            <% @exam_records = ExamRecord.where(" level = ? and correct > 0 ", lv).reorder(' correct desc, exam_records.created_at asc ').limit(6) %>
            <% @exam_records.each_with_index do |rly, index| %>
                <tr>
                  <td class="<%= index == 0 ? 'tdnumber' : 'tdnum' %>"><span><%= index + 1 %></span></td>
                  <td title="<%= (rly.name || rly.username || '') %>"><%= (rly.name || rly.username || '').truncate(5, :omission => '') %></td>
                  <td><%= rly.user.zone_province_name %></td>
                  <td><%= rly.correct %></td>
                </tr>
            <% end %>
          </table>
      <% end %>
    </div>
  </div>
  <div class="wrborbot"></div>
  <!--ranking_list end-->
</div>
<!--wrapleft end-->
<div class="clear"></div>
<!--footbox begin-->
<div class="footbox">
  <div class="bordertop">
    <dl>
      <dt><a href="javascript:void(0);"><img src="/assets/images/jz_81.jpg" width="113" height="94" /></a><a href="javascript:void(0);">各地细则 造价法规</a></dt>
      <dd><a href="javascript:void(0);">正在建设中</a></dd>
    </dl>
    <dl>
      <dt><a href="javascript:void(0);"><img src="/assets/images/jz_84.jpg" width="113" height="94" /></a><a href="javascript:void(0);">专业课堂</a></dt>
      <dd><a href="javascript:void(0);">正在建设中</a></dd>
    </dl>
    <dl>
      <dt><a href="javascript:void(0);"><img src="/assets/images/jz_90.jpg" width="142" height="94" /></a><a href="javascript:void(0);">论坛</a></dt>
      <dd><a href="javascript:void(0);">正在建设中</a></dd>
    </dl>
    <dl class="nobj">
      <dt><a href="javascript:void(0);"><img src="/assets/images/jz_87.jpg" width="142" height="94" /></a><a href="javascript:void(0);">专家活动</a></dt>
      <dd><a href="javascript:void(0);">正在建设中</a></dd>
    </dl>
  </div>
</div>
<div class="footbox_border"></div>
<!--footbox begin-->